# Create environment: `conda env create -f environment.yml`

name: ControlBootcamp

channels:
- defaults
- conda-forge

dependencies:
# Python, jupyter
- python==3.11.*
- ipykernel
- jupyterlab

# Rest
- numpy
